Repository PreOnboarding-Team-11/socialFeed, pull requests merged in 2024-08, with the labels that each got.

#4 [FEAT] User entity 와 회원가입 API 를 설계하였습니다
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/modules.xml
  .idea/modules/socialFeed.socialFeed.main~1.iml
  .idea/vcs.xml
  socialFeed/build.gradle
  socialFeed/src/main/java/backend/socialFeed/auth/config/SecurityConfig.java
  socialFeed/src/main/java/backend/socialFeed/common/dto/ErrorResponseDto.java
  socialFeed/src/main/java/backend/socialFeed/user/constant/Constants.java
  socialFeed/src/main/java/backend/socialFeed/user/controller/UserController.java
  socialFeed/src/main/java/backend/socialFeed/user/dto/JoinValidRequestDto.java
  socialFeed/src/main/java/backend/socialFeed/user/model/User.java
  socialFeed/src/main/java/backend/socialFeed/user/repository/UserRepository.java
  socialFeed/src/main/java/backend/socialFeed/user/service/UserService.java
  socialFeed/src/main/resources/application.properties
  socialFeed/src/main/resources/application.yml
Labels: ✨ FEAT

#6 [Feat] B_ENTITY_01 - article, hashtags 엔티티 작성
  socialFeed/src/main/java/backend/socialFeed/article/ArticleType.java
  socialFeed/src/main/java/backend/socialFeed/article/entity/Article.java
  socialFeed/src/main/java/backend/socialFeed/hashtags/entity/Hashtags.java
Labels: ✨ FEAT

#16 [FEAT] B_DETAIL_01 - 게시글 상세 API
  socialFeed/src/main/java/backend/socialFeed/article/controller/ArticleController.java
  socialFeed/src/main/java/backend/socialFeed/article/respotiory/ArticleRepository.java
  socialFeed/src/main/java/backend/socialFeed/article/service/ArticleService.java
Labels: ✨ FEAT

#24 [FEAT] B_DEATIL_02 - 게시글 상세 API 구현
  socialFeed/src/main/java/backend/socialFeed/article/controller/ArticleController.java
  socialFeed/src/main/java/backend/socialFeed/article/dto/ArticleResponseDto.java
  socialFeed/src/main/java/backend/socialFeed/article/entity/Article.java
  socialFeed/src/main/java/backend/socialFeed/article/respotiory/ArticleRepository.java
  socialFeed/src/main/java/backend/socialFeed/article/service/ArticleService.java
Labels: ✨ FEAT

#26 [FEAT] B_STATISTIC_01 - 통계 기능 구현
  socialFeed/.gitignore
  socialFeed/build.gradle
  socialFeed/src/main/java/backend/socialFeed/common/config/QueryDslConfig.java
  socialFeed/src/main/java/backend/socialFeed/statistic/constant/ErrorMessage.java
  socialFeed/src/main/java/backend/socialFeed/statistic/constant/StatisticType.java
  socialFeed/src/main/java/backend/socialFeed/statistic/constant/StatisticValue.java
  socialFeed/src/main/java/backend/socialFeed/statistic/controller/StatisticController.java
  socialFeed/src/main/java/backend/socialFeed/statistic/dto/StatisticRequest.java
  socialFeed/src/main/java/backend/socialFeed/statistic/dto/StatisticResponse.java
  socialFeed/src/main/java/backend/socialFeed/statistic/repository/ArticleQueryRepository.java
  socialFeed/src/main/java/backend/socialFeed/statistic/service/StatisticService.java
  socialFeed/src/main/java/backend/socialFeed/statistic/service/StatisticServiceImpl.java
Labels: ✨ FEAT

#28 [FEAT] B_ARTICLE_01 - 게시글 목록 API 구현
  socialFeed/src/main/java/backend/socialFeed/article/controller/ArticleController.java
  socialFeed/src/main/java/backend/socialFeed/article/entity/Article.java
  socialFeed/src/main/java/backend/socialFeed/article/repository/ArticleRepository.java
  socialFeed/src/main/java/backend/socialFeed/article/respotiory/ArticleRepository.java
  socialFeed/src/main/java/backend/socialFeed/article/service/ArticleService.java
  socialFeed/src/main/java/backend/socialFeed/hashtags/entity/Hashtags.java
Labels: ✨ FEAT

#25 [ETC] S_TEMPLATE_ 01 - Update issue templates
  .github/ISSUE_TEMPLATE/test.md
Labels: 📝 UPDATE

#35 [TEST] T_DETAIL_01 - 게시글 상세 기능 테스트
  socialFeed/src/test/java/backend/socialFeed/article/controller/ArticleControllerTest.java
  socialFeed/src/test/java/backend/socialFeed/article/respository/ArticleRepositoryTest.java
  socialFeed/src/test/java/backend/socialFeed/article/service/ArticleServiceTest.java
Labels: TEST

#31 [REFACTOR] B_SHARE_01 - 게시글 공유 API 구현
  socialFeed/build.gradle
  socialFeed/src/main/java/backend/socialFeed/article/ArticleType.java
  socialFeed/src/main/java/backend/socialFeed/article/config/WebClientConfig.java
  socialFeed/src/main/java/backend/socialFeed/article/controller/ShareController.java
  socialFeed/src/main/java/backend/socialFeed/article/repository/ArticleRepository.java
  socialFeed/src/main/java/backend/socialFeed/article/share/constant/ErrorMessage.java
  socialFeed/src/main/java/backend/socialFeed/article/share/service/ShareService.java
Labels: ♻️ REFACTOR

#43 Update README.md
  README.md
Labels: 📝 UPDATE
